# Generated by Django 4.2.4 on 2023-09-11 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food_toppings',
            name='food',
        ),
        migrations.AddField(
            model_name='food_toppings',
            name='category_food',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.category_food'),
        ),
    ]
